language: python
python:
  - '2.7'
before_install:
  - sudo apt-get -qq update
  - pip install --upgrade pip
  - pip install pep8 pylint
install:
  - python setup.py sdist
  - pip install ./dist/*
script:
  - pep8 botd setup.py
  - pylint botd setup.py
