language: python
python:
  - '2.7'
branches:
  only:
    - master
before_install:
  - pip install --upgrade pip
  - pip install pep8 pylint
install:
  - python setup.py sdist
  - pip install ./dist/*
script:
  - pep8 botd setup.py
  - pylint botd setup.py
