[build-system]
requires = ["setuptools ~= 59.0", "setuptools-scm[toml] ~= 6.0", "wheel ~= 0.38.0"]
build-backend = "setuptools.build_meta"

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.setuptools_scm]
