[tox]
minversion = 4.0
no_package = true
envlist =
    static
    docker

[gh-actions]
python =
    3.13: static, docker

[testenv]
setenv =
    PIPENV_IGNORE_VIRTUALENVS=1

[testenv:docker]
allowlist_externals =
    docker
commands =
    docker build .

[testenv:static]
deps =
    pipenv >= 2025
commands_pre =
    pipenv install --deploy --dev
commands =
    pipenv run black --check botd
    pipenv run flake8 botd
    pipenv run mypy botd
    pipenv run bandit --recursive botd
    pipenv run pylint botd

[flake8]
max-line-length = 88
extend-ignore = E203
